### ISSUE TITLE
Using Activator broke native ES6 functions

### ISSUE THREAD

**Issue by IvanMMM** [deitch/activator#56] opened 2018-03-03 13:36 UTC
This is caused by Styliner module dependence called 'collections'. Looks like they tried to fix it, but no results for now.

**Comment by deitch** [comment] 2018-03-04 07:25
Well, that certainly isn't good! 

@IvanMMM can you share a simple example code (gist or just pasted in here) that triggers it? And can you link to the Styliner issue?

**Comment by IvanMMM** [comment] 2018-03-04 09:48
```(javascript)
const arr = [{a:1},{a:2},{a:3}];
console.log(arr.find.toString()); //=>> function find() { [native code] }

const nodemailer = require('nodemailer');
const express = require('express');
const app = express();
const activator = require('activator');

//Создание транспорта
let transporter = nodemailer.createTransport({
    host: 'smtp.mailgun.org',
    port: 465,
    secure: true,
    auth: {
        user: 'login',
        pass: 'pass'
    }
});

//Инициализация активатора
activator.init({
    user:{},
    transport:transporter,
    from: `...`,
    templates:activator.templates.file(__dirname+'/../../templates'),
    signkey:'...',
    id:'_id',
    emailProperty:'email',
    sendPasswordResetComplete:true
});

// activate a user
app.post("/user",activator.createActivate);
app.put("/user/:user/active",activator.completeActivate);

// reset a password
app.post("/passwordreset",activator.createPasswordReset);
app.put("/passwordreset/:user",activator.completePasswordReset);

console.log(arr.find.toString());
/*
function (value, equals) {
    equals = equals || this.contentEquals || Object.equals;
    for (var index = 0; index < this.length; index++) {
        if (index in this && equals(this[index], value)) {
            return index;
        }
    }
    return -1;
}
*/
```

**Comment by deitch** [comment] 2018-03-04 09:53
I don't get it. How does the above break? If I run it, it exits (because we didn't `listen()`), but it gives sane output:

```
$ node --version
v9.3.0
$ node ./test.js
function find() { [native code] }
function find() { [native code] }
```

**Comment by IvanMMM** [comment] 2018-03-04 09:57
Hm. And here's my log
```
+ activator@3.0.1
updated 1 package in 10.793s

f:\NodeJS\STIV>node --version
v8.9.3

f:\NodeJS\STIV>node activator.js
function find() { [native code] }
function (value, equals) {
    equals = equals || this.contentEquals || Object.equals;
    for (var index = 0; index < this.length; index++) {
        if (index in this && equals(this[index], value)) {
            return index;
        }
    }
    return -1;
}
```

**Comment by deitch** [comment] 2018-03-04 09:58
Same thing if I use node `v8.6.0`

**Comment by deitch** [comment] 2018-03-04 09:59
And `8.4.0` and `8.0.0`. So it isn't that.

**Comment by deitch** [comment] 2018-03-04 09:59
I am going to clean out my `node_modules` and reinstall

**Comment by deitch** [comment] 2018-03-04 10:00
OK, now I got it. My prior `node_modules/` did not cause the problem. Probably should have kept it around. Maybe I will restore from backup.

You indicated you know the cause?

**Comment by IvanMMM** [comment] 2018-03-04 10:03
Yes. Look like guys tried to fix it, but...
https://github.com/SLaks/Styliner/issues/17

**Comment by deitch** [comment] 2018-03-04 10:04
But your sample doesn't use styliner, does it?

**Comment by deitch** [comment] 2018-03-04 10:05
And the patches there indicate that it was fixed in styliner 1.0.0?

**Comment by deitch** [comment] 2018-03-04 10:11
Not exactly. Looks like they rolled it back. [Here](https://github.com/SLaks/Styliner/pull/18/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24) is the move to q-io 2.x in Oct 2015, and [here](https://github.com/SLaks/Styliner/pull/24/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24) is the rollback in Oct 2016.

**Comment by deitch** [comment] 2018-03-04 10:28
Pushed out as 3.0.2. I don't love being forced back to precisely styliner `1.0.0` when there have been some patches since, but until their issue is resolved, at least this works.

**Closed** 2018-03-04 10:27 UTC

**Comment by IvanMMM** [comment] 2018-03-04 10:38
Great! Thank you :)
